//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ejercicioCrud.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class productos
    {
        public int Id { get; set; }
        public string nombre_Producto { get; set; }
        public string descripcion_Producto { get; set; }
        public string unid_Medida { get; set; }
        public Nullable<int> peso { get; set; }
        public Nullable<int> precio { get; set; }
    }
}
